---

- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Register node-token file access mode
  stat:
    path: /var/lib/rancher/k3s/server
  register: p

- name: Change file access node-token
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store Master node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
    key_value: ""

- name: Restore node-token file access
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"

- name: Replace https://localhost:6443 by https://master-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ master_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true

- name: Create kubectl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Create directory kube-config
  file:
    path: ~{{ ansible_user }}/kube-config
    state: directory
    owner: "{{ ansible_user }}"

- name: create Metallb namespace
  command: >-
    k3s kubectl apply -f "https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/namespace.yaml"
  changed_when: true
  when: install_metallb == "true"

- name: Install Metallb
  command: >-
    k3s kubectl apply -f "https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml"
  changed_when: true
  when: install_metallb == "true"

#this needs a check to see if it exist else it will fail if it does.
- name: Create Metallb secret
  command: >-
    kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
  changed_when: true
  when: install_metallb == "true"

- name: Copy Metallb configmap file
  template:
    src: "pool.yml.j2"
    dest: "~{{ ansible_user }}/kube-config/pool.yml"
    owner: root
    group: root
    mode: 0755
  when: install_metallb == "true"

- name: Install Metallb configmap
  command: >-
    k3s kubectl apply -f "~{{ ansible_user }}/kube-config/pool.yml"
  changed_when: true
  when: install_metallb == "true"

- name: Install k8dash
  command: >-
    k3s kubectl apply -f "https://raw.githubusercontent.com/herbrandson/k8dash/master/kubernetes-k8dash.yaml"
  changed_when: true
  when: install_k8dash == "true"

- name: Copy k8dash service
  template:
    src: "service.yml.j2"
    dest: "~{{ ansible_user }}/kube-config/service.yml"
    owner: root
    group: root
    mode: 0755
  when: install_k8dash == "true"

- name: Install k8dashlb service
  command: >-
    k3s kubectl apply -f "~{{ ansible_user }}/kube-config/service.yml"
  changed_when: true
  when: install_k8dash == "true"