---
k3s_version: v1.17.5+k3s1
ansible_user: debian
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
install_metallb: "true"
metallb_pool_name: "my-ip-space"
metallb_addresses: "192.168.1.1-192.168.1.10"
install_k8dash: "true"
